### ISSUE TITLE
hi abiee :)

### ISSUE THREAD

**Issue by breaklee** [abiee/mastering-backbone#2]
i read your book chapter 4.

there are some intresting issues.
1. more test, don't use require.js.
2. webpack etc.

so, you are not using 1, 2 issues to make web service for production?

**Comment by abiee** [comment]
Hi @breaklee,

I don't understand your questions, but I will try to give an answer. I don't use `require.js` in the book because AMD modules makes difficult to unit test your code, despite it is possible to make integration tests.

There are many options to manage and bundle dependencies in your JavaScript projects, two popular options are `browserify` and `webpack`; these tools should be decoupled from your project, which means that you should be able to switch to the other easily with the minimum changes. So choose any you feel more comfortable with.

I don't know what you mean with "2 issues to make web service for production?", can you re-ask again?

**Comment by breaklee** [comment]
@abiee 
ah, ok.
i'm a beginner for backbone.js and web service development.

There are many tools exist.
So i'm confusing which one is popular tools(package manager and bundler)
and why thery are used.

"2 isssues .... " means that you don't use require.js and webpack to make web service?

i just want to follow your way to make web service :)

**Comment by abiee** [comment]
@breaklee,

First of all, sorry for the late response, I had too much work.

I think you are confused. A web service lives in a remote server and Backbone.js code lives in the browser. Backbone.js applications normally consumes services from a REST server (the web service).

Anyway, there are many options to manage and bundle dependencies:
- [Webpack](https://github.com/webpack/webpack)
- [Browserify](https://github.com/substack/node-browserify)
- [jspm](https://github.com/jspm/jspm-cli)
- [steal.js](https://github.com/stealjs/steal)
- [require.js](https://github.com/jrburke/requirejs)
- etc.

Before web applications were JavaScript intensive, almost all the code lived at the server (i.e. PHP and ASP), on these days JavaScript was used only to improve the user experience. Then you could load your JavaScript files with the `<script>` tag.

```
<script type="text/javascript" src="jquery.js"></script>
<script type="text/javascript" src="underscore.js"></script>
<script type="text/javascript" src="backbone.js"></script>
<script type="text/javascript" src="myModel.js"></script>
<script type="text/javascript" src="myView.js"></script>
<script type="text/javascript" src="theRouter.js"></script>
<!-- ... -->
```

That works good for small project, but as your webapp grows, the complexity and relationship between scripts makes this approach difficult to follow. Imagine 100 script tags in your HTML, imagine that you change your code and now the dependency chain is different, so the order of script loading matters.

These tools to load, manage and bundle dependencies were created to solve this problem. You can put your dependencies on the script explicitly instead of put `<script>` tags in the right order.

```
var $ = require('jquery');
$.makeStuff();
```

Because the `require()` function works good on Node but not on browser environments, tools like Browserify and Webpack translates this function call into an async call to the server to fetch the right script and emulate the expected behaviour.
